[package]
name = "kinematics"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.32.5", features = ["serde", "serde-serialize"] }
serde = "1.0.197"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["full"] }

[lib]
name = "kinematics"
path = "lib.rs"
